M48
; DRILL file KiCad 10.0.3 date 2026-06-18T21:12:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-18T21:12:30+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.100
%
G90
G05
T1
X148.68Y-33.14
X148.68Y-38.92
T2
X110.58Y-77.2
X113.58Y-77.2
T3
X166.62Y-57.03
X166.62Y-59.57
X166.62Y-62.11
M30
